### ISSUE TITLE
How do you get the dataset in csv format for the repo?

### ISSUE THREAD

**Issue by RishabhJain-Github** [elastic/ember#54]

**Comment by KhenfouciYa** [comment]
@RishabhJain-Github  i have the same question could you informe me if you have any idea how we can produce the CSV format of ember dataset

**Comment by mrphilroth** [comment]
First, I'd like to say that you probably don't need the dataset in CSV format. You can read the vectorized features in with the `read_vectorized_features` function and work with the dense numpy arrays. Most model packages will accept numpy arrays as input. But assuming you've thought this through and you still need CSV features for whatever reason, here is one example of how you could do it:

```
import ember
import pandas as pd

X, y = ember.read_vectorized_features(".", "train")
df = pd.DataFrame(X)
df.to_csv("features_in_a_csv_file.csv")
```
