### ISSUE TITLE
ember2018 for unsupervised machine learning

### ISSUE THREAD

**Issue by KhenfouciYa** [elastic/ember#62]
Good morning,
could you please confirm us if i can use emebr for an unsupervised analysis like clustering.
Best Regads.

**Comment by gxenos** [comment]
The dataset contains unlabeled data, if that's what you are asking.

**Comment by KhenfouciYa** [comment]
@gxenos thank you for your quick replay , how i can extract please only  the unlabled data

**Comment by gxenos** [comment]
@KhenfouciYa You filter based on the label of each sample. The label may be 0 for benign, 1 for malicious or -1 for unlabeled. So you need the label to be -1.
