### ISSUE TITLE
 init_ember.py dataset file not found

### ISSUE THREAD

**Issue by RantoUzumaki** [elastic/ember#68]
I try to run python init_ember.py ember_data/ where init_ember.py is in same folder as ember_data and the extracted files from virusshare is there in embere_data and I get the error that
FileNotFoundError: [Errno 2] No such file or directory: 'ember_data/train_features_0.json1'

**Comment by bfilar** [comment]
Hmm... Where is your data path located? Mine is in the top-level directory so the following works for me:

```
(core) ➜  scripts git:(master) ✗ python init_ember.py ../ember2018
Creating vectorized features
WARNING: EMBER feature version 2 were computed using lief version 0.9.0-
WARNING:   lief version 0.10.1- found instead. There may be slight inconsistencies
WARNING:   in the feature calculations.
Vectorizing training set
  0%|▏                                                                             | 1644/800000 [00:16<1:56:03, 114.65it/s]
```

**Comment by RantoUzumaki** [comment]
Thanks. The error is already solved
