### ISSUE TITLE
SectionInfo & process_raw_features

### ISSUE THREAD

**Issue by ai-honzik** [elastic/ember#72]
Hi, I was going through the code and assumed (given by the [comment above](https://github.com/elastic/ember/blob/4dee42918694d72d319e731940755146a71f5c6c/ember/features.py#L167)) that line 168 in \_\_init\_\_.py should have been `sum(1 for s in sections if s['size'] != 0)`.
https://github.com/elastic/ember/blob/4dee42918694d72d319e731940755146a71f5c6c/ember/features.py#L168

Regards.

**Comment by mrphilroth** [comment]
You are absolutely correct. `!= 0` is what I intended. But using the `== 0` feature should result in the same classification performance on most ML algorithms. And the count of nonzero sections is derivable from the features. So I think I'll just bring the comment in line with the existing code and generated data. Thanks!
